name: moresleep

services:
  db:
    build: docker/postgres
    ports:
      - "5432:5432"
    volumes:
      - .postgres_data:/var/lib/postgresql/data

  service:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - ./:/src
    environment:
      - DBHOST=db
    env_file:
      - path: ./.env
        required: false