branch-defaults:
  master:
    environment: Moresleep-prod21
global:
  application_name: moresleep
  default_ec2_keyname: javabin
  default_region: eu-central-1
  profile: javabin
  sc: git
deploy:
  artifact: app.zip