name: Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: corretto
        cache: maven

    - name: Build with Maven
      run: mvn -B --no-transfer-progress clean package

    - name: Upload artifact [uber-jar]
      uses: actions/upload-artifact@v4
      with:
        name: uber-jar
        path: target/*-jar-with-dependencies.jar
        if-no-files-found: error
        retention-days: 7
